# Generated by Django 5.2.7 on 2025-10-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_place_coordinates_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='coordinates_lat',
            field=models.FloatField(max_length=255, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='place',
            name='coordinates_lng',
            field=models.FloatField(max_length=255, verbose_name='Долгота'),
        ),
    ]
